# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/nirmalk/project_3/project_3.cache/wt [current_project]
set_property parent.project_path C:/Users/nirmalk/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/nirmalk/project_3/project_3.srcs/sources_1/new/shift.v
read_xdc C:/Users/nirmalk/project_3/project_3.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files C:/Users/nirmalk/project_3/project_3.srcs/constrs_1/new/const.xdc]

synth_design -top shift -part xc7a200tfbg676-2
write_checkpoint -noxdef shift.dcp
catch { report_utilization -file shift_utilization_synth.rpt -pb shift_utilization_synth.pb }
